--#########################
--### REDs STUFF
RED_RAT_TOT_FLIGHTS = 10

local RED_rat1 = RAT:New("RAT red #001")
local RED_rat2 = RAT:New("RAT red #002")
local RED_rat3 = RAT:New("RAT red #003")
local RED_rat4 = RAT:New("RAT red #004")
local RED_rat5 = RAT:New("RAT red #005")

RED_rat1:SetCoalition("sameonly")
RED_rat2:SetCoalition("sameonly")
RED_rat3:SetCoalition("sameonly")
RED_rat4:SetCoalition("sameonly")
RED_rat5:SetCoalition("sameonly")
RED_rat1:RadioFrequency(269)
RED_rat2:RadioFrequency(269)
RED_rat3:RadioFrequency(269)
RED_rat4:RadioFrequency(269)
RED_rat5:RadioFrequency(269)
RED_rat1:ContinueJourney()
RED_rat2:ContinueJourney()
RED_rat3:ContinueJourney()
RED_rat4:ContinueJourney()
RED_rat5:ContinueJourney()
RED_rat1:SetTakeoff("cold")
RED_rat2:SetTakeoff("cold")
RED_rat3:SetTakeoff("cold")
RED_rat4:SetTakeoff("cold")
RED_rat5:SetTakeoff("cold")

local RED_manager = RATMANAGER:New(RED_RAT_TOT_FLIGHTS)
RED_manager:Add(RED_rat1)
RED_manager:Add(RED_rat2)
RED_manager:Add(RED_rat3)
RED_manager:Add(RED_rat4)
RED_manager:Add(RED_rat5)
RED_manager:Start()
--RED_manager:Stop(7200)

--#########################
--### BLUEs STUFF
BLUE_RAT_TOT_FLIGHTS = 12

local BLUE_rat1 = RAT:New("RAT blue #001")
local BLUE_rat2 = RAT:New("RAT blue #003")
local BLUE_rat3 = RAT:New("RAT blue #004")
local BLUE_rat4 = RAT:New("RAT blue #005")
local BLUE_rat5 = RAT:New("RAT blue #006")
local BLUE_rat6 = RAT:New("RAT blue #007")

BLUE_rat1:SetCoalition("sameonly")
BLUE_rat2:SetCoalition("sameonly")
BLUE_rat3:SetCoalition("sameonly")
BLUE_rat4:SetCoalition("sameonly")
BLUE_rat5:SetCoalition("sameonly")
BLUE_rat6:SetCoalition("sameonly")
BLUE_rat1:RadioFrequency(269)
BLUE_rat2:RadioFrequency(269)
BLUE_rat3:RadioFrequency(269)
BLUE_rat4:RadioFrequency(269)
BLUE_rat5:RadioFrequency(269)
BLUE_rat6:RadioFrequency(269)
BLUE_rat1:ContinueJourney()
BLUE_rat2:ContinueJourney()
BLUE_rat3:ContinueJourney()
BLUE_rat4:ContinueJourney()
BLUE_rat5:ContinueJourney()
BLUE_rat6:ContinueJourney()
BLUE_rat1:SetTakeoff("cold")
BLUE_rat2:SetTakeoff("cold")
BLUE_rat3:SetTakeoff("cold")
BLUE_rat4:SetTakeoff("cold")
BLUE_rat5:SetTakeoff("cold")
BLUE_rat6:SetTakeoff("cold")

local BLUE_manager = RATMANAGER:New(BLUE_RAT_TOT_FLIGHTS)
BLUE_manager:Add(BLUE_rat1)
BLUE_manager:Add(BLUE_rat2)
BLUE_manager:Add(BLUE_rat3)
BLUE_manager:Add(BLUE_rat4)
BLUE_manager:Add(BLUE_rat5)
BLUE_manager:Add(BLUE_rat6)
BLUE_manager:Start()
--BLUE_manager:Stop(7200)


